<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ShelvesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('shelves')->delete();

        DB::table('shelves')->insert([
            ['id' => 1,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 10],
            ['id' => 2,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 10],
            ['id' => 3,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 10],
            ['id' => 4,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 10],
            ['id' => 5,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 10],
            ['id' => 6,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 10],
            ['id' => 7,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 10],
            ['id' => 8,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 10],
            ['id' => 9,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 10],
            ['id' => 10,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 1,'capacity' => 20],
            ['id' => 11,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 10],
            ['id' => 12,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 10],
            ['id' => 13,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 10],
            ['id' => 14,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 10],
            ['id' => 15,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 10],
            ['id' => 16,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 10],
            ['id' => 17,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 10],
            ['id' => 18,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 10],
            ['id' => 19,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 10],
            ['id' => 20,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 2,'capacity' => 20],
            ['id' => 21,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 10],
            ['id' => 22,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 10],
            ['id' => 23,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 10],
            ['id' => 24,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 10],
            ['id' => 25,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 10],
            ['id' => 26,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 10],
            ['id' => 27,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 10],
            ['id' => 28,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 10],
            ['id' => 29,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 10],
            ['id' => 30,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 3,'capacity' => 20],
            ['id' => 31,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 10],
            ['id' => 32,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 10],
            ['id' => 33,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 10],
            ['id' => 34,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 10],
            ['id' => 35,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 10],
            ['id' => 36,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 10],
            ['id' => 37,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 10],
            ['id' => 38,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 10],
            ['id' => 39,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 10],
            ['id' => 40,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 4,'capacity' => 20],
            ['id' => 41,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 10],
            ['id' => 42,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 10],
            ['id' => 43,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 10],
            ['id' => 44,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 10],
            ['id' => 45,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 10],
            ['id' => 46,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 10],
            ['id' => 47,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 10],
            ['id' => 48,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 10],
            ['id' => 49,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 10],
            ['id' => 50,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 5,'capacity' => 20],
            ['id' => 51,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 10],
            ['id' => 52,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 10],
            ['id' => 53,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 10],
            ['id' => 54,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 10],
            ['id' => 55,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 10],
            ['id' => 56,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 10],
            ['id' => 57,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 10],
            ['id' => 58,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 10],
            ['id' => 59,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 10],
            ['id' => 60,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 6,'capacity' => 20],
            ['id' => 61,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 10],
            ['id' => 62,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 10],
            ['id' => 63,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 10],
            ['id' => 64,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 10],
            ['id' => 65,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 10],
            ['id' => 66,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 10],
            ['id' => 67,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 10],
            ['id' => 68,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 10],
            ['id' => 69,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 10],
            ['id' => 70,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 7,'capacity' => 20],
            ['id' => 71,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 10],
            ['id' => 72,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 10],
            ['id' => 73,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 10],
            ['id' => 74,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 10],
            ['id' => 75,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 10],
            ['id' => 76,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 10],
            ['id' => 77,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 10],
            ['id' => 78,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 10],
            ['id' => 79,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 10],
            ['id' => 80,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 8,'capacity' => 20],
            ['id' => 81,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 10],
            ['id' => 82,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 10],
            ['id' => 83,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 10],
            ['id' => 84,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 10],
            ['id' => 85,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 10],
            ['id' => 86,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 10],
            ['id' => 87,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 10],
            ['id' => 88,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 10],
            ['id' => 89,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 10],
            ['id' => 90,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 9,'capacity' => 20],
            ['id' => 91,'name' => 'E1','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 10],
            ['id' => 92,'name' => 'E2','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 10],
            ['id' => 93,'name' => 'E3','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 10],
            ['id' => 94,'name' => 'E4','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 10],
            ['id' => 95,'name' => 'E5','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 10],
            ['id' => 96,'name' => 'E6','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 10],
            ['id' => 97,'name' => 'E7','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 10],
            ['id' => 98,'name' => 'E8','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 10],
            ['id' => 99,'name' => 'E9','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 10],
            ['id' => 100,'name' => 'E10','site_id' => 1,'ray_id' => 1,'column_id' => 10,'capacity' => 20],
        ],

    );


}
}